FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY main.py ./
CMD ["python", "main.py"]

#  Мой код будет тут #
# Запускаем приложение с помощью uvicorn, делая его доступным по сети
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 